In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('/content/datasets_596958_1073629_Placement_Data_Full_Class.csv')

In [3]:
data

sl_no gender  ssc_p    ssc_b  ...  specialisation  mba_p      status    salary
0        1      M  67.00   Others  ...          Mkt&HR  58.80      Placed  270000.0
1        2      M  79.33  Central  ...         Mkt&Fin  66.28      Placed  200000.0
2        3      M  65.00  Central  ...         Mkt&Fin  57.80      Placed  250000.0
3        4      M  56.00  Central  ...          Mkt&HR  59.43  Not Placed       NaN
4        5      M  85.80  Central  ...         Mkt&Fin  55.50      Placed  425000.0
..     ...    ...    ...      ...  ...             ...    ...         ...       ...
210    211      M  80.60   Others  ...         Mkt&Fin  74.49      Placed  400000.0
211    212      M  58.00   Others  ...         Mkt&Fin  53.62      Placed  275000.0
212    213      M  67.00   Others  ...         Mkt&Fin  69.72      Placed  295000.0
213    214      F  74.00   Others  ...          Mkt&HR  60.23      Placed  204000.0
214    215      M  62.00  Central  ...          Mkt&HR  60.22  Not Placed       NaN

[215 rows x 15 columns]

##Separate Features and Target

In [4]:
x = data.drop(['status','salary'], axis=1)
y = data.iloc[:, -2]

In [5]:
x

sl_no gender  ssc_p    ssc_b  ...  workex etest_p specialisation  mba_p
0        1      M  67.00   Others  ...      No    55.0         Mkt&HR  58.80
1        2      M  79.33  Central  ...     Yes    86.5        Mkt&Fin  66.28
2        3      M  65.00  Central  ...      No    75.0        Mkt&Fin  57.80
3        4      M  56.00  Central  ...      No    66.0         Mkt&HR  59.43
4        5      M  85.80  Central  ...      No    96.8        Mkt&Fin  55.50
..     ...    ...    ...      ...  ...     ...     ...            ...    ...
210    211      M  80.60   Others  ...      No    91.0        Mkt&Fin  74.49
211    212      M  58.00   Others  ...      No    74.0        Mkt&Fin  53.62
212    213      M  67.00   Others  ...     Yes    59.0        Mkt&Fin  69.72
213    214      F  74.00   Others  ...      No    70.0         Mkt&HR  60.23
214    215      M  62.00  Central  ...      No    89.0         Mkt&HR  60.22

[215 rows x 13 columns]

In [6]:
y

0          Placed
1          Placed
2          Placed
3      Not Placed
4          Placed
          ...    
210        Placed
211        Placed
212        Placed
213        Placed
214    Not Placed
Name: status, Length: 215, dtype: object

In [7]:
x = data.drop(['status','salary'], axis=1).values

In [8]:
x

array([[1, 'M', 67.0, ..., 55.0, 'Mkt&HR', 58.8],
       [2, 'M', 79.33, ..., 86.5, 'Mkt&Fin', 66.28],
       [3, 'M', 65.0, ..., 75.0, 'Mkt&Fin', 57.8],
       ...,
       [213, 'M', 67.0, ..., 59.0, 'Mkt&Fin', 69.72],
       [214, 'F', 74.0, ..., 70.0, 'Mkt&HR', 60.23],
       [215, 'M', 62.0, ..., 89.0, 'Mkt&HR', 60.22]], dtype=object)

In [9]:
y = data.iloc[:, -2].values

In [10]:
y

array(['Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed',
       'Not Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
  

##One Hot Encoder


In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [12]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1,3,5,6,8,9,11])], remainder='passthrough')

In [13]:
x = np.array(ct.fit_transform(x))

In [14]:
x

array([[0.0, 1.0, 0.0, ..., 58.0, 55.0, 58.8],
       [0.0, 1.0, 1.0, ..., 77.48, 86.5, 66.28],
       [0.0, 1.0, 1.0, ..., 64.0, 75.0, 57.8],
       ...,
       [0.0, 1.0, 0.0, ..., 73.0, 59.0, 69.72],
       [1.0, 0.0, 0.0, ..., 58.0, 70.0, 60.23],
       [0.0, 1.0, 1.0, ..., 53.0, 89.0, 60.22]], dtype=object)

In [15]:
tab = pd.DataFrame(data=x)

In [16]:
tab

0  1  2  3  4  5  6  7  8   ... 13 14 15   16     17     18     19    20     21
0    0  1  0  1  0  1  0  1  0  ...  0  0  1    1     67     91     58    55   58.8
1    0  1  1  0  0  1  0  0  1  ...  1  1  0    2  79.33  78.33  77.48  86.5  66.28
2    0  1  1  0  1  0  1  0  0  ...  0  1  0    3     65     68     64    75   57.8
3    0  1  1  0  1  0  0  0  1  ...  0  0  1    4     56     52     52    66  59.43
4    0  1  1  0  1  0  0  1  0  ...  0  1  0    5   85.8   73.6   73.3  96.8   55.5
..  .. .. .. .. .. .. .. .. ..  ... .. .. ..  ...    ...    ...    ...   ...    ...
210  0  1  0  1  0  1  0  1  0  ...  0  1  0  211   80.6     82   77.6    91  74.49
211  0  1  0  1  0  1  0  0  1  ...  0  1  0  212     58     60     72    74  53.62
212  0  1  0  1  0  1  0  1  0  ...  1  1  0  213     67     67     73    59  69.72
213  1  0  0  1  0  1  0  1  0  ...  0  0  1  214     74     66     58    70  60.23
214  0  1  1  0  0  1  0  0  1  ...  0  0  1  215     62     58     53    89  60.22

[215 rows x 22 columns]

##Splitting Data into Train and Test sets

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [19]:
x_train

array([[0.0, 1.0, 0.0, ..., 67.0, 58.1, 75.71],
       [1.0, 0.0, 0.0, ..., 65.6, 68.0, 71.63],
       [1.0, 0.0, 0.0, ..., 69.0, 67.0, 62.35],
       ...,
       [0.0, 1.0, 0.0, ..., 54.38, 57.0, 56.13],
       [1.0, 0.0, 1.0, ..., 69.0, 55.6, 65.63],
       [0.0, 1.0, 0.0, ..., 67.0, 86.0, 70.2]], dtype=object)

In [20]:
y_train

array(['Not Placed', 'Not Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Not Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Not Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Not Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Not Placed', 'Placed',
       'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',


##Label Encoder


In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
le = LabelEncoder()

In [23]:
let = le.fit_transform(y_train)

In [24]:
let

array([0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1])

In [25]:
les = le.fit_transform(y_test)

In [26]:
les

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0])

##Standardization

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
sc = StandardScaler()

In [29]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

##Train on different algorithms

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [31]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel='rbf')

In [32]:
l_cla.fit(x_train, let)
k_cla.fit(x_train, let)
d_cla.fit(x_train, let)
r_cla.fit(x_train, let)
s_cla.fit(x_train, let)
ks_cla.fit(x_train, let)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [33]:
l_pred = l_cla.predict(x_test)
k_pred = k_cla.predict(x_test)
d_pred = d_cla.predict(x_test)
r_pred = r_cla.predict(x_test)
s_pred = s_cla.predict(x_test)
ks_pred = ks_cla.predict(x_test)

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
l_c = confusion_matrix(les, l_pred)
k_c = confusion_matrix(les, k_pred)
d_c = confusion_matrix(les, d_pred)
r_c = confusion_matrix(les, r_pred)
s_c = confusion_matrix(les, s_pred)
ks_c = confusion_matrix(les, ks_pred)

In [36]:
l_c

array([[11,  2],
       [ 4, 26]])

In [37]:
k_c

array([[ 8,  5],
       [ 6, 24]])

In [38]:
d_c

array([[ 9,  4],
       [ 2, 28]])

In [39]:
r_c

array([[ 9,  4],
       [ 4, 26]])

In [40]:
s_c

array([[11,  2],
       [ 3, 27]])

In [41]:
ks_c

array([[10,  3],
       [ 6, 24]])

In [42]:
from sklearn.metrics import accuracy_score

In [43]:
l_a = accuracy_score(les, l_pred)
k_a = accuracy_score(les, k_pred)
d_a = accuracy_score(les, d_pred)
r_a = accuracy_score(les, r_pred)
s_a = accuracy_score(les, s_pred)
ks_a = accuracy_score(les, ks_pred)

In [44]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(ks_a))

Logistic Regression: 0.8604651162790697
KNN: 0.7441860465116279
Decision Tree: 0.8604651162790697
Random Forest: 0.813953488372093
Linear SVC: 0.8837209302325582
Kernel SVC: 0.7906976744186046
