In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red.csv')

In [3]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [4]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [5]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
sc = StandardScaler()

In [10]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [12]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel='rbf')

In [13]:
l_cla.fit(x_train, y_train)
k_cla.fit(x_train, y_train)
d_cla.fit(x_train, y_train)
r_cla.fit(x_train, y_train)
s_cla.fit(x_train, y_train)
ks_cla.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [14]:
l_pred = l_cla.predict(x_test)
k_pred = k_cla.predict(x_test)
d_pred = d_cla.predict(x_test)
r_pred = r_cla.predict(x_test)
s_pred = s_cla.predict(x_test)
ks_pred = ks_cla.predict(x_test)

In [15]:
from sklearn.metrics import confusion_matrix

In [16]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [17]:
l_c

array([[ 0,  0,  1,  0,  0],
       [ 0,  1,  5,  3,  1],
       [ 1,  0, 99, 32,  1],
       [ 0,  0, 47, 74, 14],
       [ 0,  0,  2, 26, 13]])

In [18]:
k_c

array([[ 0,  0,  1,  0,  0],
       [ 0,  2,  5,  3,  0],
       [ 2,  1, 89, 39,  2],
       [ 0,  0, 39, 82, 14],
       [ 0,  0,  7, 13, 21]])

In [19]:
d_c

array([[ 0,  0,  1,  0,  0,  0],
       [ 1,  3,  2,  4,  0,  0],
       [ 1,  3, 96, 28,  5,  0],
       [ 0,  4, 37, 74, 20,  0],
       [ 0,  2,  5,  9, 22,  3],
       [ 0,  0,  0,  0,  0,  0]])

In [20]:
r_c

array([[  0,   0,   1,   0,   0,   0],
       [  1,   1,   6,   2,   0,   0],
       [  0,   0, 108,  24,   1,   0],
       [  0,   0,  35,  89,  11,   0],
       [  0,   0,   2,  12,  26,   1],
       [  0,   0,   0,   0,   0,   0]])

In [21]:
s_c

array([[  0,   0,   1,   0,   0],
       [  0,   0,   8,   2,   0],
       [  0,   0, 102,  31,   0],
       [  0,   0,  53,  82,   0],
       [  0,   0,   2,  39,   0]])

In [22]:
ks_c

array([[  0,   0,   1,   0,   0],
       [  0,   0,   7,   3,   0],
       [  0,   0, 100,  33,   0],
       [  0,   0,  44,  83,   8],
       [  0,   0,   2,  25,  14]])

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [25]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(ks_a))

Logistic Regression: 0.584375
KNN: 0.60625
Decision Tree: 0.609375
Random Forest: 0.7
Linear SVC: 0.575
Kernel SVC: 0.615625
